<?php namespace hightman\http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-16 at 11:21:36.
 */
class ClientTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Client
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Client;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers hightman\http\Client::debug
	 * @todo   Implement testDebug().
	 */
	public function testDebug()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::gzdecode
	 * @todo   Implement testGzdecode().
	 */
	public function testGzdecode()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::__destruct
	 * @todo   Implement test__destruct().
	 */
	public function test__destruct()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::setTimeout
	 * @todo   Implement testSetTimeout().
	 */
	public function testSetTimeout()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::setCookiePath
	 * @todo   Implement testSetCookiePath().
	 */
	public function testSetCookiePath()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::setParser
	 * @todo   Implement testSetParser().
	 */
	public function testSetParser()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::runParser
	 * @todo   Implement testRunParser().
	 */
	public function testRunParser()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::clearHeader
	 * @todo   Implement testClearHeader().
	 */
	public function testClearHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::head
	 * @todo   Implement testHead().
	 */
	public function testHead()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::mhead
	 * @todo   Implement testMhead().
	 */
	public function testMhead()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::get
	 * @todo   Implement testGet().
	 */
	public function testGet()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::mget
	 * @todo   Implement testMget().
	 */
	public function testMget()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::delete
	 * @todo   Implement testDelete().
	 */
	public function testDelete()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::mdelete
	 * @todo   Implement testMdelete().
	 */
	public function testMdelete()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::post
	 * @todo   Implement testPost().
	 */
	public function testPost()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::put
	 * @todo   Implement testPut().
	 */
	public function testPut()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::getJson
	 * @todo   Implement testGetJson().
	 */
	public function testGetJson()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::postJson
	 * @todo   Implement testPostJson().
	 */
	public function testPostJson()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::putJson
	 * @todo   Implement testPutJson().
	 */
	public function testPutJson()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::exec
	 * @todo   Implement testExec().
	 */
	public function testExec()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::setHeader
	 * @todo   Implement testSetHeader().
	 */
	public function testSetHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::addHeader
	 * @todo   Implement testAddHeader().
	 */
	public function testAddHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::getHeader
	 * @todo   Implement testGetHeader().
	 */
	public function testGetHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::hasHeader
	 * @todo   Implement testHasHeader().
	 */
	public function testHasHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::setRawCookie
	 * @todo   Implement testSetRawCookie().
	 */
	public function testSetRawCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::setCookie
	 * @todo   Implement testSetCookie().
	 */
	public function testSetCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::clearCookie
	 * @todo   Implement testClearCookie().
	 */
	public function testClearCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::getCookie
	 * @todo   Implement testGetCookie().
	 */
	public function testGetCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::applyCookie
	 * @todo   Implement testApplyCookie().
	 */
	public function testApplyCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Client::fetchCookieToSend
	 * @todo   Implement testFetchCookieToSend().
	 */
	public function testFetchCookieToSend()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
