<?php namespace hightman\http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-16 at 11:15:37.
 */
class ConnectionTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Connection
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Connection;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers hightman\http\Connection::connect
	 * @todo   Implement testConnect().
	 */
	public function testConnect()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Connection::findBySock
	 * @todo   Implement testFindBySock().
	 */
	public function testFindBySock()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Connection::getLastError
	 * @todo   Implement testGetLastError().
	 */
	public function testGetLastError()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Connection::close
	 * @todo   Implement testClose().
	 */
	public function testClose()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Connection::addWriteData
	 * @todo   Implement testAddWriteData().
	 */
	public function testAddWriteData()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Connection::hasDataToWrite
	 * @todo   Implement testHasDataToWrite().
	 */
	public function testHasDataToWrite()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Connection::write
	 * @todo   Implement testWrite().
	 */
	public function testWrite()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Connection::getLine
	 * @todo   Implement testGetLine().
	 */
	public function testGetLine()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Connection::read
	 * @todo   Implement testRead().
	 */
	public function testRead()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Connection::getSock
	 * @todo   Implement testGetSock().
	 */
	public function testGetSock()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Connection::getExArg
	 * @todo   Implement testGetExArg().
	 */
	public function testGetExArg()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Connection::__destruct
	 * @todo   Implement test__destruct().
	 */
	public function test__destruct()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
