<?php namespace hightman\http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-16 at 11:15:37.
 */
class ProcessorTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Processor
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Processor;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers hightman\http\Processor::__destruct
	 * @todo   Implement test__destruct().
	 */
	public function test__destruct()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Processor::getConn
	 * @todo   Implement testGetConn().
	 */
	public function testGetConn()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Processor::send
	 * @todo   Implement testSend().
	 */
	public function testSend()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Processor::recv
	 * @todo   Implement testRecv().
	 */
	public function testRecv()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Processor::finish
	 * @todo   Implement testFinish().
	 */
	public function testFinish()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
