<?php namespace hightman\http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-16 at 11:21:45.
 */
class RequestTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Request
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Request;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers hightman\http\Request::__toString
	 * @todo   Implement test__toString().
	 */
	public function test__toString()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::getMaxRedirect
	 * @todo   Implement testGetMaxRedirect().
	 */
	public function testGetMaxRedirect()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::setMaxRedirect
	 * @todo   Implement testSetMaxRedirect().
	 */
	public function testSetMaxRedirect()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::getRawUrl
	 * @todo   Implement testGetRawUrl().
	 */
	public function testGetRawUrl()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::getUrl
	 * @todo   Implement testGetUrl().
	 */
	public function testGetUrl()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::setUrl
	 * @todo   Implement testSetUrl().
	 */
	public function testSetUrl()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::getUrlParams
	 * @todo   Implement testGetUrlParams().
	 */
	public function testGetUrlParams()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::getUrlParam
	 * @todo   Implement testGetUrlParam().
	 */
	public function testGetUrlParam()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::getMethod
	 * @todo   Implement testGetMethod().
	 */
	public function testGetMethod()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::setMethod
	 * @todo   Implement testSetMethod().
	 */
	public function testSetMethod()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::getBody
	 * @todo   Implement testGetBody().
	 */
	public function testGetBody()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::setBody
	 * @todo   Implement testSetBody().
	 */
	public function testSetBody()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::setJsonBody
	 * @todo   Implement testSetJsonBody().
	 */
	public function testSetJsonBody()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::addPostField
	 * @todo   Implement testAddPostField().
	 */
	public function testAddPostField()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::addPostFile
	 * @todo   Implement testAddPostFile().
	 */
	public function testAddPostFile()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::setHeader
	 * @todo   Implement testSetHeader().
	 */
	public function testSetHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::addHeader
	 * @todo   Implement testAddHeader().
	 */
	public function testAddHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::clearHeader
	 * @todo   Implement testClearHeader().
	 */
	public function testClearHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::getHeader
	 * @todo   Implement testGetHeader().
	 */
	public function testGetHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::hasHeader
	 * @todo   Implement testHasHeader().
	 */
	public function testHasHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::setRawCookie
	 * @todo   Implement testSetRawCookie().
	 */
	public function testSetRawCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::setCookie
	 * @todo   Implement testSetCookie().
	 */
	public function testSetCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::clearCookie
	 * @todo   Implement testClearCookie().
	 */
	public function testClearCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::getCookie
	 * @todo   Implement testGetCookie().
	 */
	public function testGetCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::applyCookie
	 * @todo   Implement testApplyCookie().
	 */
	public function testApplyCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Request::fetchCookieToSend
	 * @todo   Implement testFetchCookieToSend().
	 */
	public function testFetchCookieToSend()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
