<?php namespace hightman\http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-16 at 11:21:45.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Response
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Response;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers hightman\http\Response::__toString
	 * @todo   Implement test__toString().
	 */
	public function test__toString()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::hasError
	 * @todo   Implement testHasError().
	 */
	public function testHasError()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::reset
	 * @todo   Implement testReset().
	 */
	public function testReset()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::redirect
	 * @todo   Implement testRedirect().
	 */
	public function testRedirect()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::getJson
	 * @todo   Implement testGetJson().
	 */
	public function testGetJson()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::setHeader
	 * @todo   Implement testSetHeader().
	 */
	public function testSetHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::addHeader
	 * @todo   Implement testAddHeader().
	 */
	public function testAddHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::clearHeader
	 * @todo   Implement testClearHeader().
	 */
	public function testClearHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::getHeader
	 * @todo   Implement testGetHeader().
	 */
	public function testGetHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::hasHeader
	 * @todo   Implement testHasHeader().
	 */
	public function testHasHeader()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::setRawCookie
	 * @todo   Implement testSetRawCookie().
	 */
	public function testSetRawCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::setCookie
	 * @todo   Implement testSetCookie().
	 */
	public function testSetCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::clearCookie
	 * @todo   Implement testClearCookie().
	 */
	public function testClearCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::getCookie
	 * @todo   Implement testGetCookie().
	 */
	public function testGetCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::applyCookie
	 * @todo   Implement testApplyCookie().
	 */
	public function testApplyCookie()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hightman\http\Response::fetchCookieToSend
	 * @todo   Implement testFetchCookieToSend().
	 */
	public function testFetchCookieToSend()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
